### ISSUE TITLE
downloads deprecated at 1.6

### ISSUE THREAD

**Issue by technocrat** [dlakelan/JuliaDataTutorials#4]
`using CSV,DataFrames,GMT,Printf,DataFramesMeta,Downloads

countypopurl = "https://www2.census.gov/programs-surveys/popest/datasets/2010-2020/counties/totals/co-est2020-alldata.csv"

Downloads.download(countypopurl,"countypops.csv")

cpopall = CSV.read("countypops.csv",DataFrame)
`
Adding `Downloads` to `using` and calling it fully qualified with `Downloads.download()` works

**Comment by dlakelan** [comment]
thanks for this. Easy fix, done!
